spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/materias
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict
        secure: true
      timeout: 30m